services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn myProject.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: POSTGRES_URL # Changed to match your settings.py
        fromDatabase:
          name: toms-app
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
